# Generated by Django 5.1.5 on 2025-09-23 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('license_number', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='car',
            old_name='price_per_day',
            new_name='price_per_km',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(default='Unknown Destination', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Distance in kilometers', max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.driver'),
        ),
    ]
